import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Router from 'next/router'
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { Spinner } from 'reactstrap'
import { loginAction } from '../redux/actions'
import styles from '../styles/Home.module.css'
import { API_URL } from './api/helper'

export default function Home() {

  const dispatch = useDispatch()

  const { username, iduser } = useSelector((state) => {
    console.log("cek get data", state)
    return {
      username: state.userReducer.username,
      iduser: state.userReducer.id
    }
  });

  const [loading, setLoading] = useState(false);

  const keepLogin = async () => {
    try {
      let token = JSON.parse(localStorage.getItem("next_commerce"));
      if (token.id) {
        let res = await axios.get(`${API_URL}/users?id=${token.id}`)
        dispatch(loginAction(res.data[0]))
      }
    } catch (error) {
      console.log(error)
    }
  }

  useEffect(() => {
    keepLogin()
  }, []);

  useEffect(() => {
    if(iduser){
      Router.push("/products")
    }
  });

  setTimeout(()=>setLoading(true), 2000)

  if (loading && !iduser) {
    return <div className={styles.container}>
      <Head>
        <title>Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Commerce</a>
        </h1>

        {/* <p className={styles.description}>
        Get started by editing{' '}
        <code className={styles.code}>pages/index.js</code>
      </p> */}

        <div className="d-flex">
          {/* <div className="col-6"> */}
          <a href="/login" className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Start to buy products</p>
          </a>
          {/* </div> */}
          {/* <div className="col-6"> */}
          <a href="/regis" className={styles.card}>
            <h2>Register &rarr;</h2>
            <p>Create an account</p>
          </a>
          {/* </div> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  }
  return (
    <div className='container' >
      <div className='d-flex align-items-center justify-content-center flex-column' style={{ height: "90vh" }}>
        <h5 className='text-center text-muted loading-fade' >Loading Commerce...</h5>
        <div>
          <Spinner color='primary'>
            Loading...
          </Spinner>
          <Spinner >
            Loading...
          </Spinner>
          <Spinner color='primary'>
            Loading...
          </Spinner>
        </div>
      </div>
    </div>
  )
}
